"""
Claude APIを使ったAI要約生成スクリプト
取得したニュース、X投稿、YouTube動画を要約
"""

import json
import os
from datetime import datetime
from pathlib import Path
import anthropic

# Claude API設定
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# 事故発生日
ACCIDENT_DATE = datetime(2026, 3, 16)


def load_latest_data():
    """最新データを読み込み"""
    data_dir = Path(__file__).parent.parent / "data"
    
    news = []
    youtube = []
    
    news_file = data_dir / "news-latest.json"
    if news_file.exists():
        with open(news_file, 'r', encoding='utf-8') as f:
            news = json.load(f).get('articles', [])
    
    yt_file = data_dir / "youtube-latest.json"
    if yt_file.exists():
        with open(yt_file, 'r', encoding='utf-8') as f:
            youtube = json.load(f).get('videos', [])
    
    return news, youtube


def generate_summary(news, youtube):
    """Claude APIを使って要約を生成"""
    if not ANTHROPIC_API_KEY:
        print("⚠️ ANTHROPIC_API_KEY が設定されていません")
        return None
    
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    
    today = datetime.now()
    days_since = (today - ACCIDENT_DATE).days
    
    # プロンプト作成
    news_text = "\n".join([
        f"- [{a['source']}] {a['title']} ({a['date']})\n  {a.get('excerpt', '')[:200]}"
        for a in news[:20]
    ])
    
    youtube_text = "\n".join([
        f"- [{v['channel']}] {v['title']} ({v['date']})"
        for v in youtube[:10]
    ])
    
    prompt = f"""あなたは辺野古ボート転覆事故（2026年3月16日発生）に関する報道を分析する専門家です。
本日（{today.strftime('%Y年%m月%d日')}、事故から{days_since}日目）の以下の情報を分析し、要約を生成してください。

# 取得したニュース記事
{news_text if news_text else "（記事なし）"}

# 取得したYouTube動画
{youtube_text if youtube_text else "（動画なし）"}

# 要約の形式

以下の形式で日本語で要約してください：

## 📌 今日のハイライト
（3-5項目の箇条書き、各項目は1行）

## 📝 詳細要約

### （セクション1のタイトル）
（2-3段落で詳しく）

### （セクション2のタイトル）
（必要に応じて追加）

## 💭 補足情報
（注目すべきポイント、メディア報道の傾向など）

## 今後の注目点
- （箇条書き）

---

注意事項:
- 中立的、客観的なトーンで
- 事実に基づいた情報のみ
- 推測や噂は「証言ベース」と明記
- 遺族の感情に配慮
"""
    
    print("🤖 Claude APIで要約を生成中...")
    
    message = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=2000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    summary_text = message.content[0].text
    
    return {
        "date": today.strftime('%Y-%m-%d'),
        "days_since": days_since,
        "summary": summary_text,
        "sources": {
            "news_count": len(news),
            "youtube_count": len(youtube)
        }
    }


def save_summary(summary):
    """要約を保存"""
    if not summary:
        return
    
    output_dir = Path(__file__).parent.parent / "data" / "summaries"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # JSONとして保存
    json_path = output_dir / f"{summary['date']}.json"
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
    
    # HTMLとして保存
    html_path = Path(__file__).parent.parent / "summary" / f"{summary['date']}.html"
    html_content = generate_html(summary)
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"💾 要約を保存: {summary['date']}")


def generate_html(summary):
    """要約のHTMLを生成"""
    date_formatted = datetime.strptime(summary['date'], '%Y-%m-%d').strftime('%Y年%m月%d日')
    
    # Markdown→HTML変換（簡易版）
    content = summary['summary']
    content = content.replace('\n', '<br>')
    content = content.replace('## ', '<h3>').replace('### ', '<h4>')
    
    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{date_formatted}のAI要約 | 辺野古ボート転覆事故</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <header class="header">
        <div class="header-content">
            <div>
                <h1>辺野古ボート転覆事故 報道検証</h1>
                <div class="subtitle">真相究明と再発防止のための情報集約サイト</div>
            </div>
            <nav class="nav">
                <a href="../index.html">トップ</a>
                <a href="../timeline.html">時系列詳細</a>
                <a href="../archive.html">アーカイブ</a>
                <a href="../search.html">検索</a>
                <a href="index.html" class="active">AI要約</a>
            </nav>
        </div>
    </header>
    
    <div class="container-narrow">
        <a href="index.html" style="text-decoration: none; color: #1976d2;">← AI要約一覧に戻る</a>
        
        <div class="ai-summary" style="margin-top: 2rem;">
            <h2>🤖 {date_formatted} のAI要約</h2>
            <div class="summary-meta">事故から{summary['days_since']}日目 | Generated by Claude API</div>
        </div>
        
        <div class="card">
            {content}
        </div>
    </div>
    
    <footer class="footer">
        <p>辺野古ボート転覆事故 報道検証プロジェクト</p>
        <p class="small">この要約は Claude API で自動生成されました</p>
    </footer>
</body>
</html>"""


def main():
    print("🤖 AI要約生成を開始...")
    
    news, youtube = load_latest_data()
    print(f"  - ニュース: {len(news)}件")
    print(f"  - YouTube: {len(youtube)}件")
    
    summary = generate_summary(news, youtube)
    
    if summary:
        save_summary(summary)
        print("✅ 完了")
    else:
        print("❌ 要約生成に失敗しました")


if __name__ == "__main__":
    main()
